config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :students, :except => [:show]
    resources :exams do
      member do
        patch :results, to: "exams#change_results"
      end
    end
    member do
      get :results
    end
  end

  root to: "courses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :students, :dependent => :restrict_with_error
  has_many :exams, :dependent => :restrict_with_error

  validates :year,
    presence: true,
    uniqueness: true,
    numericality: { :only_integer => true },
    length: { is: 4 },
    inclusion: { in: 1900..(Date.today + 10.years).year }

  def has_students?
    students.any?
  end

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :results, :dependent => :restrict_with_error
  belongs_to :course

  accepts_nested_attributes_for :results

  validates_presence_of :title, :date, :minimum
  validate :correct_year
  validates :minimum,
    numericality: { :greater_than_or_equal_to => 0 }
    

  def approved
    results.select(&:approved?).size
  end

  def failed
    real_results.size - self.approved
  end

  def absent_students
    course.students.size - real_results.size
  end

  def approved_percentage
    (approved * 100.00) / course.students.size
  end

  private
  def real_results
    results.select {|result| result.score.present? }
  end

  def correct_year
    errors.add(:date, "es anterior a el año del curso") unless (date.present? && date.year >= course.year)
  end

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :exam
  belongs_to :student

  validates :score,
    numericality: { :greater_than_or_equal_to => 0 },
    allow_nil: true
  validates :student, uniqueness: { scope: :exam }
  validates :exam, uniqueness: { scope: :student }

  def approved?
    score.try(:>=, exam.minimum)
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :results, :dependent => :restrict_with_error
  belongs_to :course

  validates_presence_of :first_name, :last_name, :dni, :number, :email
  validates :dni,
    length: { in: 6..11 },
    numericality: { only_integer: true }
   validates_email_format_of :email

  def to_s
    "#{first_name} #{last_name}"
  end

  def score_for(exam)
    results.where(exam_id: exam.id).take.try(:score)
  end

  def attended_to?(exam)
    self.score_for(exam).present?
  end

  def passed?(exam)
    self.score_for(exam) >= exam.minimum
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :results]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'El curso fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'El curso fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    if @course.errors.empty?
      redirect_to(courses_url, notice: 'El curso fue elimiado exitosamente.')
    else
      redirect_to(course_url, alert: 'No se puede eliminar ya que existen alumnos y/o exámenes en el curso.')
    end
  end

  def results
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:year)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exams
  before_action :set_exam, only: [:show, :edit, :update, :destroy, :change_results]

  # GET courses/1/exams/1
  def show
    @exam.course.students.each do |std|
      @exam.results.find_or_initialize_by(student: std)
    end
  end

  # GET courses/1/exams/new
  def new
    @exam = @course.exams.build
  end

  # GET courses/1/exams/1/edit
  def edit
  end

  # POST courses/1/exams
  def create
    @exam = @course.exams.build(exam_params)

    if @exam.save
      redirect_to([@exam.course, @exam], notice: 'El examen fue creado exitosamente.')
    else
      render action: 'new'
    end
  end

  # PUT courses/1/exams/1
  def update
    if @exam.update_attributes(exam_params)
      redirect_to([@exam.course, @exam], notice: 'El examen fue actualizado exitosamente.')
    else
      render action: 'edit'
    end
  end

  # DELETE courses/1/exams/1
  def destroy
    @exam.destroy
    if @exam.errors.empty?
      redirect_to(course_url(@exam.course), notice: 'El examen fue eliminado exitosamente.')
    else
      redirect_to(course_exam_url, alert: 'No se puede eliminar ya que hay notas cargadas en el examen.')
    end
  end

  def change_results
    if @exam.update(results_params)
      redirect_to(course_exam_url(@exam.course, @exam), notice: 'Las notas se actualizaron exitosamente.')
    else
      render action: 'show'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exams
      @course = Course.find(params[:course_id])
    end

    def set_exam
      @exam = @course.exams.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def exam_params
      params.require(:exam).permit(:title, :date, :minimum)
    end

    def results_params
      params.require(:exam).permit(results_attributes: [:id, :score, :student_id])
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_students
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET courses/1/students
  def index
    @students = @course.students
  end

  # GET courses/1/students/new
  def new
    @student = @course.students.build
  end

  # GET courses/1/students/1/edit
  def edit
  end

  # POST courses/1/students
  def create
    @student = @course.students.build(student_params)

    if @student.save
      redirect_to(course_students_url, notice: 'El alumno fue creado exitosamente.')
    else
      render action: 'new'
    end
  end

  # PUT courses/1/students/1
  def update
    if @student.update_attributes(student_params)
      redirect_to(course_students_url, notice: 'El alumno fue actualizado exitosamente.')
    else
      render action: 'edit'
    end
  end

  # DELETE courses/1/students/1
  def destroy
    @student.destroy
    if @student.errors.empty?
      redirect_to(course_students_url, notice: 'El alumno fue eliminado exitosamente.')
    else
      redirect_to(course_students_url, alert: 'No se puede eliminar ya que el alumno posee notas cargadas.')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students
      @course = Course.find(params[:course_id])
    end

    def set_student
      @student = @course.students.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :dni, :number, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :year, 'Año' %>
    <%= form.number_field :year, id: :course_year, class: "form-control", placeholder: "Ingrese año" %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar cursada', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Actualizar cursada</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', course_path(@course), class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form', course: @course %>
  </div>
</div>

app/views/courses/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Cursadas</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-2 col-sm-6">
     <%= link_to new_course_path do %>
          <div class="card">
            <div class="card-body">
              + Nueva cursada
            </div>
          </div>
     <% end %>
    </div>
    <% @courses.order(year: :desc).each do |course| %>
      <div class="col-lg-2 col-sm-6">
        <%= link_to course do %>
          <div class="card">
            <div class="card-body">
              <%= course.year %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Nueva cursada</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', courses_path, class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form', course: @course %>
  </div>
</div>

app/views/courses/results.html.erb
<div class="container box">
  <div class="row">
    <div class="col">
      <h1><%= @course.year %></h1>
    </div>
    <div class="col text-right">
      <%= link_to 'Atrás', course_path(@course), class: "btn btn-secondary" %>
    </div>
  </div>

  <% @exams = @course.exams.order('date') %>

  <% if @course.has_students? %>
    <div class="row">
      <table class="table table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">DNI</th>
            <th scope="col">Legajo</th>
            <% @exams.each do |exam| %>
              <th scope="col">
                <%= link_to exam.title, course_exam_path(@course, exam) %> 
              </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @course.students.each do |student| %>
            <tr>
              <td><%= student %></td>
              <td><%= student.dni %></td>
              <td><%= student.number %></td>
              <% @exams.each do |exam| %>
                <% if student.attended_to?(exam) %>
                  <% score = student.score_for(exam) %>
                  <% if student.passed?(exam) %>
                    <td class="exam-td text-success"><%= score %></td>
                  <% else %>
                    <td class="exam-td text-danger"><%= score %></td>
                  <% end %>
                <% else %>
                  <td class="exam-td text-secondary">Ausente</td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
            <tr class="table-secondary">
              <td colspan="3">Aprobados</td>
              <% @exams.each do |exam| %>
                <td scope="col"><%= exam.approved %></td>
              <% end %>
            </tr>
            <tr class="table-secondary">
              <td colspan="3">Desaprobados</td>
              <% @exams.each do |exam| %>
                <td scope="col"><%= exam.failed %></td>
              <% end %>
            </tr>
            <tr class="table-secondary">
              <td colspan="3">Ausentes</td>
              <% @exams.each do |exam| %>
                <td scope="col"><%= exam.absent_students %></td>
              <% end %>
            </tr>
            <tr class="table-secondary">
              <td colspan="3">Porcentaje de aprobación</td>
              <% @exams.each do |exam| %>
                <td scope="col"><%= number_to_percentage(exam.approved_percentage, precision: 2) %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
    <% else %>
      <div class="row">
        <div class="col">
          <div class="card mx-auto card-box" style="width: 20rem;">
            <div class="card-body text-center">
              <h4 class="card-title">Lo sentimos :(</h4>
              <h6 class="card-subtitle mb-2 text-muted">Esta cursada no dispone de estudiantes</h6>
              <i class="fas fa-exclamation-triangle empty-alert"></i>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/courses/show.html.erb
<div class="container box">
  <div class="row">
    <div class="col">
      <h1><%= @course.year %></h1>
    </div>
    <div class="col text-right">
      <%= link_to 'Editar', edit_course_path(@course), class: "btn btn-info" %>
      <%= link_to 'Eliminar', course_path(@course), :data => {:confirm => '¿Seguro desea eliminar la cursada?'}, :method => :delete, class: "btn btn-danger" %>
      <%= link_to 'Atrás', courses_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <div class="row">
    <% @course.exams.each do |exam| %>
      <div class="col-4">
        <div class="card style="width: 20rem;"">
          <div class="card-body">
            <h4 class="card-title"><%= exam.title %></h4>
            <h6 class="card-subtitle mb-2 text-muted"><%= exam.date.strftime("%m/%d/%Y") %></h6>
            <%= link_to "Ver", course_exam_path(@course, exam), class: "card-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr/>
  <div class="row">
    <div class="col">
      <%= link_to 'Nuevo examen', new_course_exam_path(@course), class: "btn btn-primary" %>
      <%= link_to 'Alumnos', course_students_path(@course), class: "btn btn-primary" %>
      <%= link_to 'Resultados', results_course_path(@course), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/exams/_form.html.erb
<%= form_for([@exam.course, @exam]) do |f| %>
  <% if @exam.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Título' %><br />
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  <div class="form-group">
    <%= f.label :date, "Fecha" %><br />
    <%= f.date_select :date, start_year: @course.year  %>
  </div>
  <div class="form-group">
    <%= f.label :minimum, 'Nota mínima' %><br />
    <%= f.number_field :minimum, class: "form-control", step: :any, placeholder: "Minimum" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Guardar examen', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Actualizar examen</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', course_exam_path(@course, @exam), class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/exams/new.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Nuevo examen</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', course_path(@course), class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/exams/show.html.erb
<div class="container box">
  <div class="row">
    <div class="col">
      <h1><%= @exam.title %></h1>
    </div>
    <div class="col text-right">
      <%= link_to 'Editar', edit_course_exam_path(@exam.course, @exam), class: "btn btn-info" %>
      <%= link_to 'Eliminar', course_exam_path(@exam.course, @exam), :data => {:confirm => '¿Seguro desea eliminar el examen?'}, :method => :delete, class: "btn btn-danger" %>
      <%= link_to "Atrás", course_path(@exam.course), class: "btn btn-secondary" %>
    </div>
  </div>
  <p>
    <b>Fecha:</b>
    <%= @exam.date.strftime("%m/%d/%Y") %>
  </p>

  <p>
    <b>Nota mínima:</b>
    <%= @exam.minimum %>
  </p>

  <div class="row">
    <div class="col">
      <% if @exam.course.has_students? %>
        <%= form_for([@exam.course, @exam], url: results_course_exam_path(@exam.course, @exam), method: :patch) do |f| %>
          <% if @exam.errors.any? %>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <ul>
              <% @exam.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          <% end %>
          <table class="table table-striped table-bordered results-table" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th scope="col">Nombre</th>
                <th scope="col">DNI</th>
                <th scope="col">Legajo</th>
                <th scope="col">Nota</th>
              </tr>
            </thead>
            <tbody>
              <%= f.fields_for :results do |result| %>
                <tr>
                  <td><%= result.object.student %></td>
                  <td><%= result.object.student.dni %></td>
                  <td><%= result.object.student.number %></td>
                  <td>
                    <div class="field">
                      <%= result.number_field :score, class: 'form-control', step: :any %>
                      <%= result.hidden_field :student_id %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="actions">
            <%= f.submit "Actualizar notas", class: 'btn btn-primary' %>
          </div>
        <% end %>
      <% else %>
        <div class="row">
          <div class="col">
            <div class="card mx-auto card-box" style="width: 20rem;">
              <div class="card-body text-center">
                <h6 class="card-subtitle mb-2 text-muted">Esta cursada no dispone de estudiantes</h6>
                <i class="fas fa-exclamation-triangle empty-alert"></i>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Sistema de administración de cursadas - Pedro Brost</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li class="alert-text">
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to "CourseManagement", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Cursadas", courses_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Cerrar sesión", destroy_user_session_path,  method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link"><img src="http://iconbug.com/data/48/512/7fed9b599abe281b110416691e400220.png" alt="Christmas hat" height="20" width="20"></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <main role="main">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for([@student.course, @student]) do |f| %>
  <% if @student.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, 'Nombre' %><br />
    <%= f.text_field :first_name, class: "form-control", placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, 'Apellido' %><br />
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  <div class="form-group">
    <%= f.label :dni, 'DNI' %><br />
    <%= f.text_field :dni, class: "form-control", placeholder: "DNI" %>
  </div>
  <div class="form-group">
    <%= f.label :number, 'Legajo' %><br />
    <%= f.text_field :number, class: "form-control", placeholder: "Number" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Guardar alumno', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Actualizar alumno</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', course_students_path(@student.course), class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/students/index.html.erb
<div class="container box">
  <div class="row">
    <div class="col">
      <h1>Alumnos</h1>
    </div>
    <div class="col-4 text-right">
      <%= link_to 'Nuevo alumno', new_course_student_path(@course), class: "btn btn-outline-primary" %>
      <%= link_to 'Atrás', course_path(@course), class: "btn btn-secondary" %>
    </div>
  </div>
  <blockquote class="blockquote">
    <p class="mb-0"><%= @course.year %></p>
  </blockquote>

  <div class="row student-table">
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>DNI</th>
          <th>Legajo</th>
          <th>Email</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Nombre</th>
          <th>DNI</th>
          <th>Legajo</th>
          <th>Email</th>
          <th>Opciones</th>
        </tr>
      </tfoot>
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td>
              <%= student %>
            </td>
            <td>
              <%= student.dni %>
            </td>
            <td>
              <%= student.number %>
            </td>
            <td>
              <%= student.email %>
            </td>
            <td>
              <%= link_to edit_course_student_path(student.course, student), class: "btn btn-outline-primary" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to [student.course, student], :data => {:confirm => '¿Seguro desea eliminar al alumno?'}, :method => :delete, class: "btn btn-outline-primary" do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
</div>
</div>

app/views/students/new.html.erb
<div class="container">
  <div class="card card-box">
    <div class="row">
      <div class="col">
        <h1>Nuevo alumno</h1>
      </div>
      <div class="col text-right">
        <%= link_to 'Atrás', course_students_path(@student.course), class: "btn btn-secondary" %>
      </div>
    </div>
    <%= render 'form' %>
  </div>
</div>